server:
  port: 8075

logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: INFO
    us.rise8.amabot: INFO

spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: true
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/amabot
    username: amabot
    password: amabot
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        show-sql: true